beer_to_beer_core_homepage:
    path:     /
    defaults: { _controller: BeerToBeerCoreBundle:Default:index }

btb_api_gps:
    path:     /api/business
    defaults: { _controller: BeerToBeerCoreBundle:Api:business }
